/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Varun' at '7/12/18 11:47 AM' with Gradle 3.0
 *
 * @author Varun, @date 7/12/18 11:47 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
