/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Varun' at '11/12/18 5:32 PM' with Gradle 3.0
 *
 * @author Varun, @date 11/12/18 5:32 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
